### ISSUE TITLE
How to solve the sitk error

### ISSUE THREAD

**Issue by chouqin3** [christianpayer/MedicalDataAugmentationTool-HeatmapRegression#2]
RuntimeError: Exception thrown in SimpleITK SmoothingRecursiveGaussianImageFilter_Execute: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.1/itkSmoothingRecursiveGaussianImageFilter.hxx:217:
itk::ERROR: itk::ERROR: SmoothingRecursiveGaussianImageFilter(0x7f6520008630): 
The number of pixels along dimension 2 is less than 4. This filter requires a minimum of four pixels along the dimension to be processed.

An error happened when processing 3d medical image, how to solve it, thank you

**Comment by christianpayer** [comment]
As the error message is saying, your processed input image has less than 4 pixels along dimension 2, which is not supported by the SmoothingRecursiveGaussianImageFilter.
`The number of pixels along dimension 2 is less than 4. This filter requires a minimum of four pixels along the dimension to be processed. This filter requires a minimum of four pixels along the dimension to be processed.`

So you would need to either images with more pixels along dimension 2, or not use the SmoothingRecursiveGaussianImageFilter in this case.

**Comment by chouqin3** [comment]
Thank you

**Comment by lowland1213** [comment]
Actually, I meet the same problem. How could I change my pixels in what kind of dimension?
