### ISSUE TITLE
the input images in the files of cep

### ISSUE THREAD

**Issue by BruceFeiFei** [christianpayer/MedicalDataAugmentationTool-HeatmapRegression#4]
Hello，can you give me the input images in the files of cep？

**Comment by christianpayer** [comment]
You can download the images from the challenge website: http://www-o.ntust.edu.tw/~cweiwang/ISBI2015/challenge1/

**Comment by Avarikqa** [comment]
Hi, the link to the website doesnt work anymore - please would you be able to advise how else I can access the data? Many thanks.
