### ISSUE TITLE
Bug in spine example: main.py

### ISSUE THREAD

**Issue by skrishnanv** [christianpayer/MedicalDataAugmentationTool-HeatmapRegression#5]
There seems to be a bug in line 249
summary_values = OrderedDict(zip(self.point_statistics_names, list(landmark_statistics.get_pe_statistics()) + landmark_statistics.get_correct_id(20)]))
I think the correct should be
summary_values = OrderedDict(zip(self.point_statistics_names,
                                         list(landmark_statistics.get_pe_statistics()) + [landmark_statistics.get**_num**_correct_id(20)]                              ) )

**Comment by christianpayer** [comment]
You are right again. Thanks for spotting this issue! I just committed the fix.

**Comment by skrishnanv** [comment]
thanks for great repo.

**Comment by skrishnanv** [comment]
thanks for great code and repo.
