### ISSUE TITLE
ImportError: No module named tensorflow_train

### ISSUE THREAD

**Issue by savanigokhale** [christianpayer/MedicalDataAugmentationTool-HeatmapRegression#6]
I get the following import error when I try to run main.py from spine folder. 

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import tensorflow_train
ImportError: No module named tensorflow_train

**Comment by christianpayer** [comment]
Hi, as stated in the Readme: You need to have the [MedicalDataAugmentationTool](https://github.com/christianpayer/MedicalDataAugmentationTool) framework downloaded and in you PYTHONPATH for the scripts to work.

To fix this problem, download the tool from [here](https://github.com/christianpayer/MedicalDataAugmentationTool) and run the `main.py` script inside the subfolder `spine`, e.g., like this:
```
PYTHONPATH=/path/to/MedicalDataAugmentationTool python main.py
```

**Comment by savanigokhale** [comment]
I missed that part while going through Readme. Thank you.
